In [3]:
#Question_1 :

liste=[]
for x in range (2000, 3201):
    if (x%7 == 0 ) and (x% 5 != 0):
        liste.append(str(x))
print(','. join(liste))

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


In [8]:
for x in range (2000, 3201):
    if (x%7 == 0) and (x%5 != 0):
        print(x,end=",")
    

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199,

In [10]:
#Question_2:

n = int(input())
fact = 1
for i in range (fact, n+1):
    fact = fact * i
print(fact)

20
2432902008176640000


In [11]:
def fact(n):
    if n == 0:
        return 1
    else:
        return n * fact(n-1)
n=int(input("Entrez un nombre pour calculer la factorielle : "))
print(fact(n))

Entrez un nombre pour calculer la factorielle : 20
2432902008176640000


In [13]:
#Question_3:

n = int(input())
dic = {}
for i in range (1, n+1):
    dic[i] = i * i
print(dic)

20
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400}


In [14]:
n = int(input())
dict = {i:i*i for i in range (1, n+1)}
print(dict)

20
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400}


In [15]:
#Question_4:

def missing_char(str, n):
    first  = str[:n]  # jusqu'à str [n-1] 
    last = str[n+1:]  # de n + 1 à la fin de la chaîne
    print(first + last)
    
missing_char('kitten', 1) #→ 'ktten'
missing_char('kitten', 0) #→ 'itten'
missing_char('kitten', 4) #→ 'kittn'


ktten
itten
kittn


In [20]:
#Question_5:

import numpy as np
x= np.arange(6).reshape(3, 2)
print("Éléments de tableau d'origine:")
print(x)
print("Tableau à lister:")
print(x.tolist())

Éléments de tableau d'origine:
[[0 1]
 [2 3]
 [4 5]]
Tableau à lister:
[[0, 1], [2, 3], [4, 5]]


In [21]:
import numpy as np
np.array([[0,1],[2,3],[4,5]]).tolist()

[[0, 1], [2, 3], [4, 5]]

In [22]:
#Question_6:


import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [23]:
#Question_7:

import math
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print(','.join(value))

100,150,180
18,22,24
